# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
ZSH_THEME="hit9"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)

# Example format: plugins=(rails git textmate ruby lighthouse)a


plugins=(zsh-autosuggestions git python pip compleat extract zsh-syntax-highlighting golang)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:$HOME/.rvm/bin

export TERM=screen-256color


# alias for reload zshrc
alias reload!='. ~/.zshrc'
# alias for quick server
alias pyserver='python -m SimpleHTTPServer'

export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

export EDITOR=vim
export TERM=screen-256color-bce

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

source $HOME/.z.sh

export PYTHON_EGG_CACHE=/tmp/py_eggs_cache

set -o emacs

sizeof(){du -h "$*"}
procofport(){lsof -n -i4TCP:"$*" | grep LISTEN}

# alias goagent="python2.7 ~/goagent/local/proxy.py"

source /usr/local/bin/virtualenvwrapper.sh

alias ssdb-server=/usr/local/ssdb/ssdb-server
alias ssdb-cli=/usr/local/ssdb/ssdb-cli


# only mac
export PATH=$PATH:$(brew --prefix)/share/npm/bin
# only ruby
source $HOME/.rvm/scripts/rvm

export NODE_PATH=/usr/local/lib/node_modules

# fuck clang 5.1
export ARCHFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future"
#export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages
[[ -s "/Users/hit9/.gvm/scripts/gvm" ]] && source "/Users/hit9/.gvm/scripts/gvm"
source "/Users/hit9/github/oo/env"
export GOPATH=/Users/hit9/gospace
export PATH=$PATH:$GOPATH/bin

export NVM_DIR="/Users/hit9/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
export PATH=$PATH:/Users/hit9/.cargo/bin
export PATH=$PATH:/Users/hit9/toolchain/gcc-arm-none-eabi-5_3-2016q1/bin
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
